<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital.Services.Interface\Hospital.Services.Interface.csproj" />
    <ProjectReference Include="..\Hospital.Services\Hospital.Services.csproj" />
    <ProjectReference Include="..\Hospital.Models.Data\Hospital.Models.Data.csproj" />
    <ProjectReference Include="..\Hospital.Repositories.Interface\Hospital.Repositories.Interface.csproj" />
    <ProjectReference Include="..\Hospital.Repositories.EF\Hospital.Repositories.EF.csproj" />
    <ProjectReference Include="..\Hospital.Data.EF\Hospital.Data.EF.csproj" />
  </ItemGroup>

</Project>
